theme: jekyll-theme-cayman
title: Daniel Schmitz
description: danielschmitz.com.br
logo: https://avatars0.githubusercontent.com/u/1509692?s=460&v=4
show_downloads: false
github:
  is_project_page: false
